FROM node:20-slim

WORKDIR /app

# 依存関係をインストール
COPY frontend/package.json frontend/package-lock.json ./
RUN npm install


ARG VITE_API_BASE_URL
ENV VITE_API_BASE_URL=$VITE_API_BASE_URL

ARG VITE_FRONTEND_ALLOWED_HOSTS
ENV VITE_FRONTEND_ALLOWED_HOSTS=$VITE_FRONTEND_ALLOWED_HOSTS

# アプリのソースをコピー
COPY frontend/ .


# ビルド（Vite）
RUN npm run build

ENV NODE_ENV=production
ENV PORT=8080

EXPOSE 8080

# Viteの本番プレビューサーバーで起動
CMD ["npm", "run", "preview", "--", "--port", "8080", "--host"] 