version: '3.8'

services:
  # --- idea-discussion ---
  idea-frontend:
    container_name: idea-frontend-dev
    image: node:20-alpine # Use a base image, Vite runs on host via volume mount
    working_dir: /app
    volumes:
      - ./idea-discussion/frontend:/app
      # Add node_modules volume to prevent host node_modules from overwriting container's
      - /app/node_modules
    ports:
      - "5173:5173" # Expose Vite dev server port
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0" # Install deps if needed and run dev server
    env_file:
      - .env # Load environment variables from .env file
    environment:
      - NODE_ENV=development
      - VITE_API_BASE_URL=${IDEA_FRONTEND_API_BASE_URL} # Use variable from .env

  idea-backend:
    container_name: idea-backend-dev
    build:
      context: ./idea-discussion/backend
      dockerfile: Dockerfile.dev
    volumes:
      - ./idea-discussion/backend:/app
      # Prevent host node_modules from overwriting container's
      - /app/node_modules
    ports:
      - "3000:3000" # Expose backend API port
    depends_on:
      - mongo
    env_file:
      - .env # Load environment variables from .env file
    environment:
      - NODE_ENV=development
      # Override MONGODB_URI for Docker network
      - MONGODB_URI=mongodb://mongo:27017/idea_discussion_db # Use service name 'mongo'
      # Explicitly pass GitHub and OpenRouter variables from .env
      - GITHUB_APP_ID=${GITHUB_APP_ID}
      - GITHUB_APP_PRIVATE_KEY=${GITHUB_APP_PRIVATE_KEY}
      - GITHUB_INSTALLATION_ID=${GITHUB_INSTALLATION_ID}
      - GITHUB_TARGET_OWNER=${GITHUB_TARGET_OWNER}
      - GITHUB_TARGET_REPO=${GITHUB_TARGET_REPO}
      - GITHUB_BASE_BRANCH=${GITHUB_BASE_BRANCH}
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
    command: npm run dev # Command defined in Dockerfile.dev, but explicit here

  # --- policy-edit ---
  policy-frontend:
    container_name: policy-frontend-dev
    image: node:20-alpine # Use a base image, Vite runs on host via volume mount
    working_dir: /app
    volumes:
      - ./policy-edit/frontend:/app
      # Add node_modules volume
      - /app/node_modules
    ports:
      - "5174:5173" # Expose Vite dev server port (Host: 5174, Container: 5173)
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0" # Install deps if needed and run dev server
    env_file:
      - .env # Load environment variables from .env file
    environment:
      - NODE_ENV=development
      - VITE_API_BASE_URL=${POLICY_FRONTEND_API_BASE_URL} # Use variable from .env
      # Map GITHUB_TARGET_* from .env to VITE_GITHUB_* for the frontend
      - VITE_GITHUB_REPO_OWNER=${GITHUB_TARGET_OWNER}
      - VITE_GITHUB_REPO_NAME=${GITHUB_TARGET_REPO}

  policy-backend:
    container_name: policy-backend-dev
    build:
      context: . # Change context to the root directory
      dockerfile: ./policy-edit/backend/Dockerfile # Specify Dockerfile path relative to new context
      target: production             # Build the production stage
    ports:
      - "3001:3001" # Expose backend API port
    env_file:
      - .env # Load environment variables from .env file
    environment:
      - NODE_ENV=development
      # Ensure CORS allows the frontend origin (running on host port 5174)
      - CORS_ORIGIN=http://localhost:5174
    # Run the production start command
    command: npm start

  # --- Database ---
  mongo:
    container_name: mongo-dev
    image: mongo:latest
    ports:
      - "27017:27017" # Expose MongoDB port to host (optional, for external tools)
    volumes:
      - mongo_data:/data/db # Persist data using a named volume

volumes:
  mongo_data:                  # Define the named volume for MongoDB
  # Removed node_modules volumes as they are part of the production image
