name: Deploy User (Reusable)

on:
  workflow_call:
    inputs:
      repository:
        required: true
        type: string
      api_base_url:
        required: true
        type: string
      service_url:
        required: true
        type: string
    secrets:
      WIF_PROVIDER:
        required: true
      WIF_SERVICE_ACCOUNT:
        required: true

env:
  PROJECT_ID: daikibo-jyukugi-cdp
  REGION: asia-northeast1
  SERVICE_NAME: user

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      id-token: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
        service_account: ${{ secrets.WIF_SERVICE_ACCOUNT }}

    - name: Configure Docker
      run: |
        gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev

    - name: Build and Push
      uses: docker/build-push-action@v5
      with:
        context: .
        file: cloud-run/docker/Dockerfile.user
        platforms: linux/amd64
        push: true
        tags: |
          ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ inputs.repository }}/${{ env.SERVICE_NAME }}:latest
          ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ inputs.repository }}/${{ env.SERVICE_NAME }}:${{ github.sha }}
        build-args: |
          VITE_API_BASE_URL=${{ inputs.api_base_url }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Deploy Complete
      run: |
        echo "✅ Deployment complete!"
        echo "🔗 Service URL: ${{ inputs.service_url }}"