name: check

on: [push, pull_request]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: npm install
      # TODO: tsc
      - name: lint
        run: npm run lint:all
      - name: test
        run: npm run test:all
